#! /bin/bash

set -x

echo "==> Adding user 'nitrux'."

groupadd sambashare

useradd -G adm,cdrom,sudo,dip,plugdev,bluetooth,lpadmin,sambashare,input -m nitrux || true
printf "%s\n" nitrux nitrux | passwd nitrux
